export const DOWNLOAD_REASON_NO_PATH_SET = "NO_WOW_PATH_SET";
export const DOWNLOAD_REASON_INSTALL = "INSTALL";
export const DOWNLOAD_REASON_SYMLINK = "IS_SYMLINK";
export const DOWNLOAD_REASON_UPDATE = "UPDATE";
export const DOWNLOAD_REASON_UP_TO_DATE = "UP_TO_DATE";
